services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend/x-clone:/usr/src/app
      - /usr/src/app/node_modules # ホスト側の node_modules を無視
    ports:
      - "5173:5173"
    tty: true
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend/x-backend:/usr/src/app
      - /usr/src/app/node_modules # ホスト側の node_modules を無視
    ports:
      - '3000:3000'
    tty: true


