services:
  frontend:
    build:
      context: ./apps/frontend
      dockerfile: Dockerfile
    volumes:
      - ./apps/frontend:/usr/src/app
      - /usr/src/app/node_modules # ホスト側の node_modules を無視
    ports:
      - "5173:5173"
    tty: true
  backend:
    build:
      context: ./apps/backend
      dockerfile: Dockerfile
    volumes:
      - ./apps/backend:/usr/src/app
      - /usr/src/app/node_modules # ホスト側の node_modules を無視
    ports:
      - '3000:3000'
    tty: true


