services:
  frontend:
    build:
      context: .
      dockerfile: DockerFile
      target: frontend
    volumes:
      - ./apps/frontend:/dev/app/packages/frontend
    ports:
      - "5173:5173"
    tty: true
  backend:
    build:
      context: .
      dockerfile: DockerFile
      target: backend
    volumes:
      - ./apps/backend:/dev/app/packages/backend
    ports:
      - '3000:3000'
    tty: true


