services:
  frontend:
    build:
      context: .
      dockerfile: DockerFile
      target: frontend
    volumes:
      - ./apps/frontend:/app/packages/frontend
      - /app/packages/frontend/node_modules # ホスト側の node_modules を無視
    ports:
      - "5173:5173"
    tty: true
  backend:
    build:
      context: .
      dockerfile: DockerFile
      target: backend
    volumes:
      - ./apps/backend:/app/packages/backend
      - /app/packages/backend/node_modules # ホスト側の node_modules を無視
    ports:
      - '3000:3000'
    tty: true


